### PR TITLE
tab autocompletion

### LINKED ISSUE #169: tab autocompletion
Consider using https://github.com/mklabs/node-tabtab

### PR DESCRIPTION
**Pull request by tsriram**
Using tabtab for auto-completion of cheminfo

Should close #169

### CODE REVIEW

**Review by maasencioh — CHANGES_REQUESTED** [review]
Hello @tsriram, I try to use it in zsh and in bash and it's not autocompleting, how did you test it?

**Comment by tsriram** [comment]
@maasencioh did you try uninstalling the old one and install this? Hope there was no (permission related) error during installation.  Once I install this globally, I opened a new terminal and pressing tab twice after `cheminfo` show 4 options given in package.json. I tried it in bash. You may want to check if there's a line `tabtab source for cheminfo package` towards the end in `~/.bashrc`

**Comment by maasencioh** [comment]
In .bashrc I have

``` bash
# tabtab source for cheminfo-tools package
# uninstall by removing these lines or running `tabtab uninstall cheminfo-tools`
[ -f /home/maasencioh/git/cheminfo/tools/node_modules/tabtab/.completions/cheminfo-tools.bash ] && . /home/maasencioh/git/cheminfo/tools/node_modules/tabtab/.completions/cheminfo-tools.bash
```

In .zshrc I have:

``` bash
# tabtab source for cheminfo-tools package
# uninstall by removing these lines or running `tabtab uninstall cheminfo-tools`
[[ -f /home/maasencioh/git/cheminfo/tools/node_modules/tabtab/.completions/cheminfo-tools.zsh ]] && . /home/maasencioh/git/cheminfo/tools/node_modules/tabtab/.completions/cheminfo-tools.zsh
```

Can you confirm if you have the same? because I have this with npm link I I'm not sure if that could be the problem

Thanks!

**Comment by tsriram** [comment]
I have this in .bashrc
`[ -f /home/sriram/.nvm/versions/node/v5.6.0/lib/node_modules/cheminfo-tools/node_modules/tabtab/.completions/cheminfo.bash ] && . /home/sriram/.nvm/versions/node/v5.6.0/lib/node_modules/cheminfo-tools/node_modules/tabtab/.completions/cheminfo.bash`

Not sure why you have cheminfo-tools.bash at the end! How are you installing this? from my repo?

**Comment by tsriram** [comment]
Any luck with this @maasencioh?

**Comment by maasencioh** [comment]
After looking some time apparently it's taking the name of the package, so it takes `cheminfo-tools` instead of `cheminfo`, so for example for bash the command looks like:

``` bash
###-begin-cheminfo-tools-completion-###
if type complete &>/dev/null; then
  _cheminfo-tools_completion () {
    local words cword
    if type _get_comp_words_by_ref &>/dev/null; then
      _get_comp_words_by_ref -n = -n @ -w words -i cword
    else
      cword="$COMP_CWORD"
      words=("${COMP_WORDS[@]}")
    fi

    local si="$IFS"
    IFS=$'\n' COMPREPLY=($(COMP_CWORD="$cword" \
                           COMP_LINE="$COMP_LINE" \
                           COMP_POINT="$COMP_POINT" \
                           cheminfo-tools completion -- "${words[@]}" \
                           2>/dev/null)) || return $?
    IFS="$si"
  }
  complete -o default -F _cheminfo-tools_completion cheminfo-tools
fi
###-end-cheminfo-tools-completion-###
```

but it works when you change it to:

``` bash
###-begin-cheminfo-tools-completion-###
if type complete &>/dev/null; then
  _cheminfo-tools_completion () {
    local words cword
    if type _get_comp_words_by_ref &>/dev/null; then
      _get_comp_words_by_ref -n = -n @ -w words -i cword
    else
      cword="$COMP_CWORD"
      words=("${COMP_WORDS[@]}")
    fi

    local si="$IFS"
    IFS=$'\n' COMPREPLY=($(COMP_CWORD="$cword" \
                           COMP_LINE="$COMP_LINE" \
                           COMP_POINT="$COMP_POINT" \
                           cheminfo completion -- "${words[@]}" \
                           2>/dev/null)) || return $?
    IFS="$si"
  }
  complete -o default -F _cheminfo-tools_completion cheminfo
fi
###-end-cheminfo-tools-completion-###
```

**Comment by maasencioh** [comment]
I think that in the issue mklabs/node-tabtab#29 they suggest you to use `--name cheminfo`, it could solve it

**Comment by tsriram** [comment]
@maasencioh yea, I thought I pushed that change but missed it somehow. Have just pushed it. It should work now, hopefully. Sorry for wasting your time :frowning_face:

**Review by maasencioh — APPROVED** [review]

**Comment by maasencioh** [comment]
@tsriram it wasn't a waist at all, I learn a lot in the way, thanks for your contribution and now it's working perfectly :smile:

**Pull request merged**
